#!/bin/bash
# downloads the drug database from Fimea and converts it to UTF-8

wget -O drugs.csv http://www.fimea.fi/documents/160140/1128399/pakkaus1.txt/1fdad9d7-7933-4cb5-b459-fed2eb25b32d
iconv -f ISO-8859-15 -t UTF-8 drugs.csv > drugs.utf8
rm drugs.csv
mv drugs.utf8 drugs.csv

wget -O packages.csv http://www.fimea.fi/documents/160140/1128399/pakkaus_nolla.txt/8ad67660-6860-40eb-8056-159fcc863d60
iconv -f ISO-8859-15 -t UTF-8 packages.csv > packages.utf8
rm packages.csv
mv packages.utf8 packages.csv

