#!/bin/bash
# removes names with . % and digits from the drug names

#remove dots
cat names.txt | grep -v '\.' > names.san
rm names.txt
mv names.san names.txt

#remove %
cat names.txt | grep -v % > names.san
rm names.txt
mv names.san names.txt

#remove numbers
cat names.txt | grep -v '[0-9]' > names.san
rm names.txt
mv names.san names.txt

